CREATE TABLE IF NOT EXISTS settings (
    key_name VARCHAR(128) PRIMARY KEY,
    value_text TEXT NOT NULL,
    updated_by VARCHAR(64) NOT NULL,
    updated_at DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS user_profiles (
    user_id CHAR(36) PRIMARY KEY,
    picture_data_url MEDIUMTEXT NULL,
    updated_at DATETIME NOT NULL,
    CONSTRAINT fk_profile_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS access_logs (
    id CHAR(36) PRIMARY KEY,
    actor VARCHAR(64) NOT NULL,
    source_ip VARCHAR(128) NOT NULL,
    method VARCHAR(16) NOT NULL,
    path VARCHAR(512) NOT NULL,
    status_code INT NOT NULL,
    details_json JSON NOT NULL,
    created_at DATETIME NOT NULL
);

ALTER TABLE tls_keys ADD COLUMN IF NOT EXISTS cert_level VARCHAR(32) NOT NULL DEFAULT 'leaf';
ALTER TABLE tls_keys ADD COLUMN IF NOT EXISTS parent_cert_id CHAR(36) NULL;
ALTER TABLE tls_keys ADD COLUMN IF NOT EXISTS cipher VARCHAR(64) NOT NULL DEFAULT 'ed25519';
ALTER TABLE tls_keys ADD COLUMN IF NOT EXISTS key_length INT NOT NULL DEFAULT 256;
ALTER TABLE tls_keys ADD COLUMN IF NOT EXISTS usages_json JSON NULL;

ALTER TABLE ssh_keys ADD COLUMN IF NOT EXISTS ssh_username VARCHAR(128) NULL;
ALTER TABLE ssh_keys ADD COLUMN IF NOT EXISTS machine_name VARCHAR(255) NULL;
ALTER TABLE ssh_keys ADD COLUMN IF NOT EXISTS cipher VARCHAR(64) NOT NULL DEFAULT 'ed25519';
ALTER TABLE ssh_keys ADD COLUMN IF NOT EXISTS key_length INT NOT NULL DEFAULT 256;
