ALTER TABLE root_ca ADD COLUMN IF NOT EXISTS organization VARCHAR(255) NOT NULL DEFAULT 'Internal Lab';
ALTER TABLE root_ca ADD COLUMN IF NOT EXISTS description TEXT NULL;

ALTER TABLE tls_keys ADD COLUMN IF NOT EXISTS allow_private_key_export BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE ssh_keys ADD COLUMN IF NOT EXISTS allow_private_key_export BOOLEAN NOT NULL DEFAULT TRUE;
