ALTER TABLE root_ca ADD COLUMN IF NOT EXISTS is_revoked BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE root_ca ADD COLUMN IF NOT EXISTS revoked_at DATETIME NULL;
ALTER TABLE root_ca ADD COLUMN IF NOT EXISTS revoked_reason VARCHAR(255) NULL;
