ALTER TABLE root_ca ADD COLUMN IF NOT EXISTS country VARCHAR(2) NULL;

ALTER TABLE root_ca ADD COLUMN IF NOT EXISTS state VARCHAR(128) NULL;

ALTER TABLE root_ca ADD COLUMN IF NOT EXISTS locality VARCHAR(128) NULL;

ALTER TABLE root_ca ADD COLUMN IF NOT EXISTS org_unit VARCHAR(128) NULL;
