CREATE TABLE IF NOT EXISTS ssh_cas (
    id CHAR(36) PRIMARY KEY,
    ca_type VARCHAR(8) NOT NULL,
    name VARCHAR(128) NOT NULL,
    algorithm VARCHAR(32) NOT NULL,
    public_key TEXT NOT NULL,
    private_key_enc MEDIUMTEXT NOT NULL,
    fingerprint_sha256 VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_by VARCHAR(64) NOT NULL,
    created_at DATETIME NOT NULL,
    INDEX ix_ssh_cas_type (ca_type, is_active)
);
CREATE TABLE IF NOT EXISTS ssh_certificates (
    id CHAR(36) PRIMARY KEY,
    ca_id CHAR(36) NOT NULL,
    ca_type VARCHAR(8) NOT NULL,
    cert_type VARCHAR(8) NOT NULL,
    serial BIGINT UNSIGNED NOT NULL,
    key_id VARCHAR(255) NOT NULL,
    principals TEXT NOT NULL,
    critical_options TEXT NULL,
    extensions TEXT NULL,
    subject_public_key TEXT NOT NULL,
    certificate TEXT NOT NULL,
    private_key_enc MEDIUMTEXT NULL,
    allow_private_key_export BOOLEAN NOT NULL DEFAULT TRUE,
    fingerprint_sha256 VARCHAR(255) NOT NULL,
    machine_id CHAR(36) NULL,
    ssh_key_id CHAR(36) NULL,
    valid_from DATETIME NOT NULL,
    valid_to DATETIME NOT NULL,
    created_by VARCHAR(64) NOT NULL,
    created_at DATETIME NOT NULL,
    is_revoked BOOLEAN NOT NULL DEFAULT FALSE,
    revoked_at DATETIME NULL,
    revoked_reason VARCHAR(255) NULL,
    INDEX ix_ssh_certificates_ca (ca_id),
    INDEX ix_ssh_certificates_machine (machine_id)
)
