ALTER TABLE applications ADD COLUMN IF NOT EXISTS default_use_sudo BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE applications ADD COLUMN IF NOT EXISTS default_staging_dir VARCHAR(512) NULL;

ALTER TABLE applications ADD COLUMN IF NOT EXISTS is_retired BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE host_applications ADD COLUMN IF NOT EXISTS use_sudo TINYINT(1) NULL;

ALTER TABLE host_applications ADD COLUMN IF NOT EXISTS staging_dir VARCHAR(512) NULL;
